export const profile = {
  name: 'Adiel Ribeiro',
  fullName: 'Adiel Ribeiro do Vale Junior',
  email: 'adiel.rv@gmail.com',
  github: 'https://github.com/adielribeiro',
  linkedin: 'https://www.linkedin.com/in/adiel-ribeiro-do-vale-j%C3%BAnior-b5094574/',
  cv: `${import.meta.env.BASE_URL}Curriculo_Adiel_Ribeiro_do_Vale_Junior.pdf`,
}
export const projects = [
  { id: 'rfq', category: 'Corporativo', title: 'Compras conectadas, do início ao fim.', name: 'Automação de RFQ', description: 'Um fluxo de cotação que conecta compradores, fornecedores e SAP Business One.', stack: ['n8n', 'SAP B1', 'Service Layer', 'JavaScript'], status: 'Entregue · 2026', problem: 'Conectar o envio de solicitações, a resposta dos fornecedores e o registro das cotações em um processo consistente para três empresas.', solution: 'Automação com n8n, formulário web por empresa e integração com SAP Business One Service Layer. Validações de CNPJ, moeda, prazo, recusa e controle de duplicidade.', result: 'Fluxo entregue para Kimberlit, Bionat e Loyder, com respostas registradas no SAP e notificações ao comprador.', private: true },
  { id: 'duplicatas', category: 'Corporativo', title: 'Documentos financeiros em movimento.', name: 'Envio de duplicatas', description: 'Integração de documentos, assinatura digital e notificações ao cliente.', stack: ['C#', '.NET', 'SQL Server', 'SOAP'], status: 'Projeto corporativo', problem: 'Organizar o envio de duplicatas e acompanhar o estado dos documentos entre diferentes sistemas.', solution: 'Integração entre SAP Business One e SoftExpert, geração de PDF, regras de elegibilidade, histórico de integração e acompanhamento de assinatura.', result: 'Rotina automatizada com rastreabilidade de envio e consulta ao status dos documentos.', private: true },
  { id: 'ptax', category: 'Corporativo', title: 'Cotações integradas ao ERP.', name: 'SAPCurrencyRate.API', description: 'Serviço de atualização cambial com dados PTAX do Banco Central.', stack: ['.NET 6', 'SAP B1', 'API BCB'], status: 'Projeto corporativo', problem: 'Atualizar a cotação utilizada pelo ERP com uma rotina consistente e passível de acompanhamento.', solution: 'Serviço em .NET com consulta PTAX, horário de corte, controle de repetição e registro do tipo de cotação e horário da consulta.', result: 'Atualização de taxas no SAP Business One com execução idempotente e regras de horário.', private: true },
  { id: 'orcafeito', category: 'Autoral', title: 'Da proposta ao próximo negócio.', name: 'Orça Feito', description: 'Projeto de produto para criar e organizar orçamentos comerciais.', stack: ['React', 'API', 'Pagamentos'], status: 'Projeto autoral', problem: 'Ajudar prestadores de serviço a preparar e compartilhar orçamentos comerciais.', solution: 'Desenvolvimento da interface, API e experiência de um produto por assinatura, com estudo de integração de pagamentos.', result: 'Projeto com repositórios públicos de interface e API.', url: 'https://github.com/adielribeiro/gerador-orcamentos', extraUrl: 'https://github.com/adielribeiro/orcamentos-api' },
  { id: 'sequencia', category: 'Autoral', title: 'Uma boa jogada acontece em tempo real.', name: 'Sequência', description: 'Jogo de cartas multiplayer com regras e estado controlados pelo servidor.', stack: ['React', 'Node.js', 'Socket.IO'], status: 'Protótipo', problem: 'Sincronizar partidas de cartas entre vários jogadores, respeitando regras e turnos.', solution: 'Cliente React conectado a um servidor Node.js/Express via Socket.IO, com salas, cartas especiais e adversários controlados pelo computador.', result: 'Base jogável para partidas em rede de dois a quatro participantes.', url: 'https://github.com/adielribeiro/sequencia-card-game' },
  { id: 'partitura', category: 'Autoral', title: 'Código a serviço da música.', name: 'Partitura Web', description: 'Editor de partituras que aproxima minha experiência com música e desenvolvimento.', stack: ['React', '.NET 8', 'PDF'], status: 'MVP em desenvolvimento', problem: 'Explorar uma experiência web para editar partituras e organizar instrumentos.', solution: 'MVP com edição de notas, pausas e compassos, múltiplas claves, metadados e exportação em PDF.', result: 'Projeto em desenvolvimento, com foco em interação e organização de partituras.' },
]
export const experience = [
  { period: '2021 — atual', title: 'Desenvolvedor Back-end', company: 'Grupo Essere', detail: 'Kimberlit · Bionat · Loyder', text: 'APIs e serviços em C#/.NET, integrações com SAP Business One, SoftExpert e Sênior. Automação de processos com n8n, workflows, formulários e assinatura digital. Do levantamento de requisitos à implantação.', stack: ['C# / .NET', 'SQL Server', 'SAP B1', 'SoftExpert', 'n8n'] },
  { period: 'fev — jun 2021', title: 'Tecnologia da Informação', company: 'ACIRP Rio Preto', text: 'Suporte a usuários e sistemas, administração de acessos e desenvolvimento web com PHP, HTML e JavaScript.', stack: ['PHP', 'JavaScript', 'Git'] },
  { period: '2017 — 2020', title: 'Facilitador de TI', company: 'Aurora Alimentos', text: 'Infraestrutura, redes, telefonia e suporte à operação. Controle de ativos de software e atendimento aos usuários.', stack: ['Infraestrutura', 'Redes', 'Suporte'] },
  { period: '2015 — 2017', title: 'Técnico em Informática', company: 'Rework', text: 'Suporte técnico, manutenção de impressoras, infraestrutura e redes.', stack: [] },
  { period: '2008 — 2015', title: 'Assistente de TI', company: 'Móveis Província', text: 'Manutenção de computadores, servidores Linux e Windows e apoio à implantação do SAP Business One.', stack: ['Linux', 'Windows', 'SAP B1'] },
]
